version: '2.0'
services:
  db1:
    image: postgres
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123qwe
    volumes:
      - ./db1/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  db2:
    image: postgres
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123qwe
    volumes:
      - ./db2/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8000:15672"

  command:
    build: ./command
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: db1
      POSTGRES_DB: db1
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123qwe
    links:
      - rabbit
      - db1
    depends_on:
      - rabbit
      - db1
      
  query:
    build: ./query
    ports:
      - 3001:3001
    environment:
      POSTGRES_HOST: db2
      POSTGRES_DB: db2
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123qwe
    links:
      - rabbit
      - db2
    depends_on:
      - rabbit
      - db2
  